### ISSUE TITLE
Item Quantity Issue

### ISSUE THREAD

**Issue by tarang9211** [mrvautin/expressCart#9]
Hi Guys,

In your example demo, I can set the item quantity to be a negative amount. Just something I came across. Let me know if you need a PR.

**Comment by mrvautin** [comment]
Ah good find! Please submit PR, that would be very helpful.

**Comment by tarang9211** [comment]
Completely new to the repo. Could you let me know what file I should be looking at?

**Comment by tarang9211** [comment]
Any update on this @mrvautin?

**Comment by hardikmodi1** [comment]
I have checked that bug is fixed but it will automatically remove the item from the cart when it reached negative amount and refresh the page, But the user may press it one more time by mistake so it should not remove the item from cart automatically just not subtract anything if the quantity is already zero

**Comment by mrvautin** [comment]
Finally getting a chance to look into this now. Fix will be done soon.

**Comment by mrvautin** [comment]
Fixed in: c674f8657685f06da5a6a9d68cfecf533e25945f

**Comment by shubham0109** [comment]
Are the changes not made in example demo. It's still showing negative values
